@server = http://localhost:3000 

### 게시글 조회 
GET {{server}}/blog

### 게시글 생성 
POST {{server}}/blog
Content-Type: application/json

{
    "title": "test",
    "content": "test",
    "name": "test"
}

### 게시글 상세 조회
GET {{server}}/blog/1

### 게시글 수정
PUT {{server}}/blog/1
Content-Type: application/json

{
    "title": "test2",
    "content": "test2",
    "name": "test2"
}

### 게시글 삭제
DELETE {{server}}/blog/1
